providers:
  - id: 'file://tests/promptfoo_test_runner.py'

tests:
  - file://tests/promptfoo_tests/deepseek-v3_tests.yaml
  - file://tests/promptfoo_tests/deepseek_r1_tests.yaml


columns:
  - name: prompt
    path: vars.prompt

  - name: model
    path: vars.model

  - name: submission
    path: vars.submission_file

  - name: solution
    path: vars.solution_file

  - name: output
    path: output
