providers:
  - id: 'file://tests/promptfoo_test_runner.py'

prompts: ./prompts.yaml

columns:
  - name: prompt
    path: vars.prompt

  - name: model
    path: vars.model

  - name: submission
    path: vars.submission_file

  - name: solution
    path: vars.solution_file

  - name: output
    path: output
