providers:
  - id: exec:python3 -m ai_feedback
    config:
      command: >
        --scope code
        --submission {{vars.submission_file}}
        --solution {{vars.solution_file}}
        --model deepSeek-v3
        --llama_mode server
        --prompt {{vars.prompt}}
        --prompt_text "{{input}}"

#  - id: exec:python3 -m ai_feedback
#    config:
#      command: >
#        --scope code
#        --submission {{vars.submission_file}}
#        --solution {{vars.solution_file}}
#        --model deepSeek-R1:70B
#        --prompt {{vars.prompt}}
#        --prompt_text "{{input}}"
