providers:
  - id: 'file://promptfoo_test_runner.py'

tests:
  - file:///tests/deepseek_r1_tests/deepseek_v3_code_tests.yaml
  - file:///tests/deepseek_v3_tests/deepseek_r1_code_tests.yaml


columns:
  - name: prompt
    path: prompt

  - name: prompt_template
    path: vars.prompt

  - name: model
    path: vars.model

  - name: submission
    path: vars.submission_file

  - name: solution
    path: vars.solution_file

  - name: output
    path: output
